config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'rooms/show'
  get 'rooms/index', to: 'rooms#index'
  get 'search', to: 'main#search' #get :search, controller: :main
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
  post 'likes/up', to: "likes#up"
  post 'likes/down', to: "likes#down"
  get 'likes/show/like/:id', to: "likes#show_likes", as: 'likes_show_like'
  get 'likes/show/dislike/:id', to: "likes#show_dislikes", as: 'likes_show_dislike'

  resources :comments
  get 'pics/:id', to: "pics#show"
  delete 'pics/:id', to: "pics#del",  as: 'pics_del'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'posts/profile/:id', to: "posts#profile", as: 'user_profile'
  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/test', to: 'application#test'

  post '/upload_profile_pic', to: 'users#upload_profile_pic'
  delete '/delete_profile_pic', to: 'users#delete_profile_pic'
  post '/update_profile', to: 'users#update_profile'
  get '/edit_profile', to: 'users#edit_profile'
  get '/edit_name', to: 'users#edit_name'
  post '/update_name', to: 'users#update_name'
  
  mount ActionCable.server => '/cable'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# This class controls CRUD operation for feature/comment
class CommentsController < ApplicationController
  respond_to :html, :js
  
  def create
    @cmt = Comment.new(permit_comment)
    @cmt.user_id = current_user.id
    if @cmt.save
      flash[:success] = 'Success'
    else
      flash[:error] = @cmt.errors.full_messages
    end
  end

  def destroy
    @cmt = Comment.find(params[:id])
    if @cmt.destroy
      flash[:success] = 'Success'
    else
      flash[:error] = @cmt.errors.full_messages
    end   
  end

  def edit
    @cmt = Comment.find(params[:id])
  end

  def update
    @cmt = Comment.find(params[:id])
    if @cmt.update(permit_comment)
      flash[:success] = 'Success'
    else
      flash[:error] = @cmt.errors.full_messages
    end
  end

  private

  def permit_comment
    params.require(:comment).permit(:description, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit_comments.html.erb
<div class="col-lg-12" id="edit_comments<%=@cmt.post.id%>">
  <br>
    <%= form_for(@cmt, remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      
        <div class="col-lg-9">
          <div class="form-group">
          <%= f.text_area :description, rows: 1, class: "form-control", autofocus: true %>
        </div>
      </div>
      <div class="col-lg-2 " style="display: inline;margin-left: 10px;">
        <div class="form-group">
          <%= f.submit :"Update Comment",  class: "btn btn-primary btn-md" %>
        </div>
      </div>
    <% end %>
</div>

app/views/comments/_form_comments.html.erb
<div class="col-lg-12" id="form_comments<%=post.id%>">
  <br>
    <%= form_for(Comment.new, remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <%= f.hidden_field :post_id, :value => post.id %>
        <div class="col-lg-10">
          <div class="form-group">
            <img src="<%=User.find(post.user_id).image.url%>" style="width:9%;height:35px;float: left;border-radius: 50%;">
            <%= f.text_area :description, rows: 1, class: "form-control", placeholder: "Please enter a comment", autofocus: true, style: "width: 400px; margin-left: 50px;" %>
        </div>
      </div>
    <div class="col-lg-1 ">
        <div class="form-group">
          <%= f.submit :Comment,  class: "btn btn-primary btn-md" %>
        </div>
      </div>
    <% end %>
</div>

app/views/comments/_show_comments.html.erb
<div id="show_comments<%=post.id%>">
  <% if post.comments != [] %> 
   <div class="col-lg-12" id="show_comments<%=post.id%>" style="overflow:scroll; height: 200px;">
     <% post.comments.each do |comment| %>
      <br><br>
          
      <div class="col-lg-10">
        <img src="<%=User.find(comment.user_id).image.url%>" style="width:7%;height:30px;float: left;border-radius: 50%;">
          <mark class="friend-mark"  style="margin-left: 5px; margin-top: 1px;"  >
            <b><%= link_to "#{User.find(comment.user_id).full_name}", user_profile_path(comment.user_id) %></b>
            <%= comment.description %>
          </mark>
       
      </div>
        <% if user_signed_in? and comment.user_id == current_user.id %>
          <div class="col-lg-2" style="float: right;">
            <%= link_to "", edit_comment_path(comment), remote: true, style: "margin-left: 25px;", class: "fas fa-edit", title: "Edit comment"  %>
             <%= link_to "", comment, remote: true , method: :delete, data: { confirm: 'Are you sure?' }, style: "float: right", class: "fas fa-trash", title: "Delete comment"%>
           </div>
        <% elsif user_signed_in? and current_user.posts.include?(post)%>
          <div class="col-lg-2" style="float: right;">
             <%= link_to "", comment, remote: true , method: :delete, data: { confirm: 'Are you sure?' }, style: "float: right", class: "fas fa-trash", title: "Delete comment"%>
           </div>
        <% end %>
      <% end %> 
    </div> 
  <% end %>
  <div class="col-lg-12">
    <% if user_signed_in? %>
      <!-- Form for comments   -->
        <%= render partial: "comments/form_comments", locals: {post: post} %>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$('#show_comments<%=@cmt.post.id%>').replaceWith("<%= j render partial: 'comments/show_comments', locals: {post: @cmt.post} %>");
$('#form_comments<%=@cmt.post.id%>').replaceWith("<%= j render partial: 'comments/form_comments', locals: {post: @cmt.post} %>");

app/views/comments/destroy.js.erb
$('#show_comments<%=@cmt.post.id%>').replaceWith("<%= j render partial: 'comments/show_comments', locals: {post: @cmt.post} %>");
$('#edit_comments<%=@cmt.post.id%>').replaceWith("<%= j render partial: 'comments/form_comments', locals: {post: @cmt.post} %>");

app/views/comments/edit.js.erb
$("#form_comments<%=@cmt.post.id%>").replaceWith("<%= j render partial: 'comments/edit_comments' %>");

app/views/comments/update.js.erb
$('#show_comments<%=@cmt.post.id%>').replaceWith("<%= j render partial: 'comments/show_comments', locals: {post: @cmt.post} %>");
$('#edit_comments<%=@cmt.post.id%>').replaceWith("<%= j render partial: 'comments/form_comments', locals: {post: @cmt.post} %>");