config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'rooms/show'
  get 'rooms/index', to: 'rooms#index'
  get 'search', to: 'main#search' #get :search, controller: :main
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
  post 'likes/up', to: "likes#up"
  post 'likes/down', to: "likes#down"
  get 'likes/show/like/:id', to: "likes#show_likes", as: 'likes_show_like'
  get 'likes/show/dislike/:id', to: "likes#show_dislikes", as: 'likes_show_dislike'

  resources :comments
  get 'pics/:id', to: "pics#show"
  delete 'pics/:id', to: "pics#del",  as: 'pics_del'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'posts/profile/:id', to: "posts#profile", as: 'user_profile'
  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/test', to: 'application#test'

  post '/upload_profile_pic', to: 'users#upload_profile_pic'
  delete '/delete_profile_pic', to: 'users#delete_profile_pic'
  post '/update_profile', to: 'users#update_profile'
  get '/edit_profile', to: 'users#edit_profile'
  get '/edit_name', to: 'users#edit_name'
  post '/update_name', to: 'users#update_name'
  
  mount ActionCable.server => '/cable'
  
end

app/models/user.rb
# frozen_string_literal: true

# Model for Users
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :posts
  has_many :messages
  has_many :comments
  has_many :likes
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_attached_file :image, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def already_likes?(post_id)
    self.likes.where(post_id: post_id).size > 0
  end

  #This method tries to find an existing user by the provider and uid fields
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.full_name = auth.info.name 
    #user.last_name = auth.info.last_name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    end
  end

  
 # def self.from_omniauth(access_token)
    #data = access_token.info
    #user.email = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
     #unless user
       #  user = User.create(name: data['name'],
        #    email: data['email'],
         #   password: Devise.friendly_token[0,20]
         #)
     #end
    #user
#end

# to reset and confirm email
  def send_devise_notification(notification, *args)
   devise_mailer.send(notification, self, *args).deliver_later
 end

  # to copy data from session whenever a user is initialized before sign up, we just need to implement new_with_session in our model
  #def self.new_with_session(params, session)
    #super.tap do |user|
     # if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      #  user.email = data["email"] if user.email.blank?
      #end
    #end
  #end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
  #def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
   # @user = User.from_omniauth(request.env["omniauth.auth"])

    #if @user.persisted?
     # sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      #set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    #else
     # session["devise.facebook_data"] = request.env["omniauth.auth"]
      #redirect_to new_user_registration_url
    #end
  #end

  ## redirect_to root_path
  #end



  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def upload_profile_pic
    current_user.image = params[:image]
    current_user.save
  end

  def delete_profile_pic
    current_user.image.destroy
    current_user.save
  end

  def update_profile
    current_user.age = params[:select_age]
    current_user.gender = params[:select_gender]
    current_user.save
  end

  def edit_profile
  end

  def update_name
    current_user.full_name = params[:full_name]
    current_user.save
  end

end

app/views/users/_edit_name.html.erb
<div id="update_name<%=current_user.id%>">
  <%= form_tag update_name_path,remote: true, method: :post do %>
    <%= text_field_tag :full_name, current_user.full_name %>
    <%= submit_tag 'Update', class: 'black'%>
  <% end %>
</div>

app/views/users/_edit_profile.html.erb
<div id="update_profile<%=current_user.id%>">
    <%= form_tag update_profile_path, remote: true, method: :post do %>
      <%= select_tag 'select_gender', options_for_select([ "Gender", "Male", "Female", "Others" ], current_user.gender)%>
      <%= select_tag 'select_age', options_for_select((1..100).to_a.unshift('Age'), selected: current_user.age)%>
    <%= submit_tag 'Update', class: 'black'%>
  <% end %>
</div>

app/views/users/_profile_pic.html.erb
 <div class="col-lg-12" id="image_upload<%=current_user.id%>" onmouseover="iconAppear();" onmouseout="iconDisappear();" >
  <img src="<%=current_user.image.url%>" style="width:95%;height: 300px; cursor: pointer;" onClick="profileImageClick();">

    <% if current_user.image_file_name != nil %>
       <%= link_to "", delete_profile_pic_path,remote: true, method: :delete, id: "icon_appear", class: "fas fa-trash fa-2x", style: "position: absolute;top: 5px; left: 260px; opacity: 0;", data: {confirm: "Are you sure?"}, title: "Delete image" %>
    <%end%>
    <input type="file" id="profile_image_input" style="opacity: 0;" onChange="imageInputChange();">
</div> 

app/views/users/_update_name.html.erb
<div id="edit_name<%=current_user.id%>" > 
    <h3>
      <%= current_user.full_name %>
      <%= link_to "", edit_name_path(current_user), remote: true, class: "fas fa-edit", title: "Edit"  %>
    </h3>
</div>

app/views/users/_update_profile.html.erb
<div id="edit_profile<%=current_user.id%>">
  <h4>
    <%= current_user.gender %>,
    <%= current_user.age %>
    <%= link_to "", edit_profile_path, remote: true, style: "margin-left: 25px;", class: "fas fa-edit", title: "Edit"  %>
  </h4>
  
</div>
      

app/views/users/delete_profile_pic.js.erb
$('#image_upload<%=current_user.id%>').replaceWith("<%= j render partial: 'users/profile_pic'  %>");

app/views/users/edit_name.js.erb
$('#edit_name<%=current_user.id%>').html("<%= j render partial: 'users/edit_name'  %>");

app/views/users/edit_profile.js.erb
$('#edit_profile<%=current_user.id%>').replaceWith("<%= j render partial: 'users/edit_profile'  %>");

app/views/users/update_name.js.erb
$('#update_name<%=current_user.id%>').replaceWith("<%= j render partial: 'users/update_name' %>");

app/views/users/update_profile.js.erb
$('#update_profile<%=current_user.id%>').replaceWith("<%= j render partial: 'users/update_profile' %>");

app/views/users/upload_profile_pic.js.erb
$('#image_upload<%=current_user.id%>').replaceWith("<%= j render partial: 'users/profile_pic'  %>");