config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'rooms/show'
  get 'rooms/index', to: 'rooms#index'
  get 'search', to: 'main#search' #get :search, controller: :main
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
  post 'likes/up', to: "likes#up"
  post 'likes/down', to: "likes#down"
  get 'likes/show/like/:id', to: "likes#show_likes", as: 'likes_show_like'
  get 'likes/show/dislike/:id', to: "likes#show_dislikes", as: 'likes_show_dislike'

  resources :comments
  get 'pics/:id', to: "pics#show"
  delete 'pics/:id', to: "pics#del",  as: 'pics_del'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'posts/profile/:id', to: "posts#profile", as: 'user_profile'
  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/test', to: 'application#test'

  post '/upload_profile_pic', to: 'users#upload_profile_pic'
  delete '/delete_profile_pic', to: 'users#delete_profile_pic'
  post '/update_profile', to: 'users#update_profile'
  get '/edit_profile', to: 'users#edit_profile'
  get '/edit_name', to: 'users#edit_name'
  post '/update_name', to: 'users#update_name'
  
  mount ActionCable.server => '/cable'
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def show
    @messages = Message.where(friend_id: params[:format], 
      user_id: current_user.id).or(Message.where(friend_id: current_user.id,
      user_id:params[:format] ))
    @messages.update_all(is_read: true)
  end

  def index
    @friends = current_user.friends
  end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<% if @friends %>
  <h2 class="lead text-center">Select user to send messages!</h2>
  <br>
  <% @friends.each do |friend| %>
    <div class="col-lg-5"></div>
    <div class="col-lg-3">
      <mark class="friend-mark"><b></b><%= link_to "#{friend.full_name}", rooms_show_path(friend) %></mark>
      <span class="badge badge-light" style="background-color: red;    position: absolute;top: 8px;left: 55%;"><%= friend.messages.where(friend_id: current_user.id, is_read: false).count %></span>
    
    </div>
    <br><br>
  <%end%>
<%else%>
  <h2 class="lead text-center">Start Adding friends to send messages!</h2>
<%end%>

app/views/rooms/show.html.erb
<div class="main container">
  
  <div class="message-history" id="messages">
    <%= render @messages %>
  </div>
</div>
<div class="input-box container" style="margin-top: 20px;">
  <mark style="background-color: #27AE60;border-radius: 6px; color: white; font-size: 18px; "><%= current_user.full_name %></mark>
  <span style="margin-left: 20px;">
    <input type="text" placeholder="Enter your message here" class="input-box_text" id="message_input" style="width: 500px; " onkeypress="sendMessage(event, <%=params[:format]%>);" />
  </span>
</div>