config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'rooms/show'
  get 'rooms/index', to: 'rooms#index'
  get 'search', to: 'main#search' #get :search, controller: :main
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
  post 'likes/up', to: "likes#up"
  post 'likes/down', to: "likes#down"
  get 'likes/show/like/:id', to: "likes#show_likes", as: 'likes_show_like'
  get 'likes/show/dislike/:id', to: "likes#show_dislikes", as: 'likes_show_dislike'

  resources :comments
  get 'pics/:id', to: "pics#show"
  delete 'pics/:id', to: "pics#del",  as: 'pics_del'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'posts/profile/:id', to: "posts#profile", as: 'user_profile'
  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/test', to: 'application#test'

  post '/upload_profile_pic', to: 'users#upload_profile_pic'
  delete '/delete_profile_pic', to: 'users#delete_profile_pic'
  post '/update_profile', to: 'users#update_profile'
  get '/edit_profile', to: 'users#edit_profile'
  get '/edit_name', to: 'users#edit_name'
  post '/update_name', to: 'users#update_name'
  
  mount ActionCable.server => '/cable'
  
end

app/models/post.rb
# frozen_string_literal: true

# Model for Posts
class Post < ApplicationRecord
  belongs_to :user
  has_many :pics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @posts = []
    if user_signed_in?
      @posts << current_user.posts if current_user.posts
      current_user.friends.each do |friend|
        @posts << friend.posts
      end
    else
      @posts << Post.all.order(created_at: :desc)
    end
    @posts.flatten!.sort_by!{|e| -e[:created_at].to_i}

  end

  def profile
    @user = User.find(params[:id])
    @posts = []
    if user_signed_in?
      @posts << current_user.posts if current_user.posts
      current_user.friends.each do |friend|
        @posts << friend.posts
      end
    else
      @posts << Post.all.order(created_at: :desc)
    end
    @posts.flatten!.sort_by!{|e| -e[:created_at].to_i}
  end
  
  def destroy
    Post.find(params[:id]).destroy   
      redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update 
      post = Post.find(params[:id])
      if post.update(permit_post)
        if params[:post][:image]
          params[:post][:image].each do |pic|
            img = Pic.new(permit_image)
            img.post_id = params[:id]
            img.image = pic
            img.save
          end
        end
        flash[:success] = "Success"
        redirect_to post_path(post)
      else
        flash[:error] = post.errors.full_messages
        redirect_to new_post_path
      end
  end 

  def show
      @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(permit_post)
    @post.user_id = current_user.id
      if @post.save
        params[:post][:image].each do |pic|
          img = Pic.new(permit_image)
          img.post_id = @post.id
          img.image = pic
          img.save
        end  
        flash[:success] = "Success"
        redirect_to post_path(@post)
      else
        flash[:error] = @post.errors.full_messages
        redirect_to new_post_path
      end  
  end

#TO prevent sql injection, ensures user can only edit image(s) and descriptions only.  
  private 
    def permit_post
       params.require(:post).permit(:description) 
    end

    def permit_image
       params.require(:post).permit(:image) 
    end
 

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts.html.erb
<% if !@posts.empty? %>
  <% @posts.each do |post| %> 
    <div class="col-lg-12" style="background-color: white; border-radius: 10px; margin-bottom: 25px;">
      <br>
      <div class="col-lg-12 " >
        <div class="col-lg-9">
        <span>
        <img src="<%=User.find(post.user_id).image.url%>" style=" float:left;width:10%;height:48px;border-radius: 50%;margin-right: 5px;margin-top: 15px;">
        <br>
        <%= link_to "#{post.user.full_name}", user_profile_path(post.user) %> 
        <i  class="fas fa-envelope"></i>
        </span> 
        <br>
        <%= post.created_at %>
        </div>
        <div class="col-lg-3">
          <% if user_signed_in? and current_user.id == post.user_id %>
            <div class="col-lg-12 text-right " style="margin-top: 30px;">

               <%= link_to "", edit_post_path(post), class: "fas fa-edit", title: "Edit post" %>
              <%= link_to "", post, method: :delete, data: {confirm: "Are you sure?"}, class: "fas fa-trash", style: "margin-left: 5px;", title: "Delete post" %>
            </div>
          <% end %>
        </div> 
      </div>
      <br><br><br><br>
      <div class="col-lg-12 slide-pic">
          <ul class="bxslider">
            <%  post.pics.each do |pic| %>
              <li>
                <a class="sb"  href="<%= pic.image.url %>"> <%= image_tag(pic.image.url, size: "800x400") %> </a>
              </li>

            <% end %>
          </ul>
      </div>

        
        <div class="col-lg-12 lead">
          <%= post.description %>
        </div>
        
      
      <!-- like and dislike counts and form -->
      <div class="col-lg-12">  
        <%= render partial: "likes/likes_count", locals: {post: post} %> 
        <%= render partial: "likes/like_form", locals: {post: post} %>

        <%= render partial: "likes/dislikes_count", locals: {post: post} %>
        <%= render partial: "likes/dislike_form", locals: {post: post} %> 
      </div>
    <!--  Showing Comments  -->
      <%= render partial: "comments/show_comments", locals: {post: post} %>
  
  </div>
<% end %> 

<% else %>
  <div class="col-lg-12">
    <h1 >Start adding friends and posts today!</h1>
  </div>
<% end %> 

app/views/posts/edit.html.erb
<div class="col-lg-12 container">
<h2 class="lead">Edit Post</h2>
  <% @post.pics.each do |pic| %>
    <div class="col-lg-3">
      <a href="/pics/<%=pic.id%>"><%= image_tag(pic.image.url, size: "200x200") %></a>
      <br>
      <%= link_to "", pics_del_path(pic), method: :delete,style: "margin-left: 90px;",class: "fas fa-trash", data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>
</div>
  <div class="col-lg-12">
  <%= form_for @post, html: {multipart: true} do |f| %>
    <br>
    <%= f.label :"Add new image(s):" %>
    <%= f.file_field(:image, :multiple => true, class: "btn btn-mini" )  %>
    <div id="uniq"> </div>
    <br>
    <%= f.label :"Update description:" %>
    <br>
    <%= f.text_area(:description, size: "50*50")  %>
    <br>
    <%= f.submit :Update,class: "btn btn-primary" %>
  <% end %> 
</div>

<script type="text/javascript">
  $(document).ready(function(){
    function readURL(input) {
      for(i=0;i<input.files.length;i++){
      if (input.files && input.files[i]) {
        var reader = new FileReader();
            
        reader.onload = function (e) {
            $('#uniq').prepend('<li style="display: inline;"> <img src=" '+e.target.result+' " height="200" width="200" /> </li>')
            }
            
            reader.readAsDataURL(input.files[i]);
        }
      } 
    }
     $("#post_image").change(function(){
        readURL(this);  });
  });
</script>


<style type="text/css">
  img {
      border-radius: 8px;
  }

</style>
  

app/views/posts/index.html.erb
<div class="col-lg-2"></div>
<div class="col-lg-6 ">
  <%= render partial: "posts/posts"%> 
</div>
<div class="col-lg-3" style="overflow:scroll; height: 200px; right: 0;margin-right: 25px;margin-top: 48px; background-color: white; border-radius: 10px; position: fixed;">

    <% if user_signed_in? %>
      <br>

      <p class="lead" style="background-color: #D0D3D4; border-radius: 5px;color: #154360;"><b>People you may know</b></p>
      <% User.all.each do |user| %>
        <% if current_user.friends.include?(user)%>
          <!-- <mark class="friend-mark" > <b><%= user.full_name %></b></mark>
          <i class="fas fa-check" style="float: right; margin-top: 10px;"></i> -->
          <% next %>
        <% elsif user == current_user %>
          <% next %>
        <% elsif current_user.friend_requests.find_by(friend_id: user.id) || user.friend_requests.find_by(friend_id: current_user.id) %>
          <% next %>
        <% else%>
          <img src="<%=user.image.url%>" style="width:40px; height: 40px;float: left;border-radius: 50%;">
          <mark class="friend-mark" style= " margin-top: 8px; margin-left: 5px;" > <b><%= link_to "#{user.full_name}", user_profile_path(user) %></b></mark>
              <%= link_to "Add friend", friend_requests_path(user), method: :post, style: "float: right; margin-top: 8px;", class: "black" %>
            
        <%end%>
        <br><br>
      <% end %>
    <% end %>

  </div>
</div>      
  
<script>
  $(document).ready(function(){
    $('.bxslider').bxSlider();
  });
</script>

app/views/posts/new.html.erb
<div class="col-lg-12 container">
  <h3 class="lead">New post</h3>
  <%= form_for @post, html: {multipart: true} do |f| %>
 
    <%= f.file_field(:image, :multiple => true, class: "btn btn-mini" ) %>
          <div  id="uniq" >
          </div>
          <br>
    <%= f.text_area(:description, size: "50*50")  %>
    <br>
    <%= f.submit :Post, class: "btn btn-primary", style: "margin-bottom: 30px;" %>

<% end %> 
  
</div>


<script type="text/javascript">
  $(document).ready(function(){
    function readURL(input) {
      for(i=0;i<input.files.length;i++){
      if (input.files && input.files[i]) {
        var reader = new FileReader();
            
        reader.onload = function (e) {
            //$('#blah').attr('src', e.target.result);
            $('#uniq').prepend('<li style="display: inline;"> <img src=" '+e.target.result+' " height="200" width="200" /> </li>')
            }
            
            reader.readAsDataURL(input.files[i]);
        }
      } 
    }
     $("#post_image").change(function(){
        readURL(this);  });
  });
</script>

<style type="text/css">

  img {
      border-radius: 8px;
      }

</style>

app/views/posts/profile.html.erb
<div class="col-lg-12" style="background-color: #EAECEE">
  <div class="col-lg-3 card" style="margin-left:10px;margin-bottom: 10px;border-radius: 10px; background-color: white;position: fixed;">
    <br>
    <div class="col-lg-12" id="image_upload<%=current_user.id%>" onmouseover="iconAppear();" onmouseout="iconDisappear();" >
      <img src="<%=@user.image.url%>" style="width:95%;height: 300px; cursor: pointer;" onClick="profileImageClick();" >
      <% if current_user == @user %>
        <% if current_user.image_file_name != nil %>
           <%= link_to "", delete_profile_pic_path,remote: true, method: :delete, id: "icon_appear", class: "fas fa-trash fa-2x", style: "position: absolute;top: 5px; left: 260px; opacity: 0;", data: {confirm: "Are you sure?"}, title: "Delete image" %>
        <%end%>
        <input type="file" id="profile_image_input" style="opacity: 0;" onChange="imageInputChange();">
      <%end%>
    </div> 


    <div class="col-lg-12">
           
      <div id="edit_name<%=@user.id%>" >
         <h3>
          <%= @user.full_name %>
          <% if current_user == @user %>
            <%= link_to "", edit_name_path(@user), remote: true, class: "fas fa-edit", title: "Edit"  %>
          <%end%>
         </h3>     
      </div>
      <h4> <%= @user.email %></h4>
      <% if @user.age == nil and @user.age == nil %>
        <% if current_user == @user %>
          <%= render partial: "users/edit_profile"%>
        <% end %>
      <% else %>
        <div id="edit_profile<%=@user.id%>">
          <h4>
            <%= @user.gender %>, <%= @user.age %>
            <% if current_user == @user %>
              <%= link_to "", edit_profile_path, remote: true, style: "margin-left: 25px;", class: "fas fa-edit", title: "Edit"  %>
            <% end %>  
          </h4>
        </div>
      <% end %>
      <%= link_to "View Friends", friends_index_path(@user), class: "fas fa-user-friends"%>
      <div class="col-lg-12">
        <!-- <a href="#"><i class="fa fa-dribbble"></i></a> 
        <a href="#"><i class="fa fa-twitter"></i></a>  
        <a href="#"><i class="fa fa-linkedin"></i></a>  
        <a href="#"><i class="fa fa-facebook"></i></a> 
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-google"></i></a>  -->  
        <br>
        <% if current_user.friends.include?(@user)%>
          <%= link_to "Remove friend", friends_destroy_path(@user), data: {confirm: "Are you sure?"}, class: "black" %>
        <% elsif @user == current_user %>
        <% elsif current_user.friend_requests.find_by(friend_id: @user.id) %> 
          <%= link_to "Cancel request",  current_user.friend_requests.find_by(friend_id: @user.id), method: :delete, data: {confirm: "Are you sure?"}, class: "black" %>
        <% elsif @user.friend_requests.find_by(friend_id: current_user.id) %>
          <%= link_to "Accept",  @user.friend_requests.find_by(friend_id: current_user.id), method: :patch, class: "black" %>
          <%= link_to "Decline",  @user.friend_requests.find_by(friend_id: current_user.id), method: :delete, data: {confirm: "Are you sure?"}, class: "black" %>
        <% else%>
          <%= link_to "Add friend", friend_requests_path(@user), method: :post, class: "black" %> 
        <%end%>
        <br>
        

     </div>
    </div>
  </div>
  <div class="col-lg-7" style="float: right;">
     <%= render partial: "posts/posts"%> 
  </div>

</div>

<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 350px;
  height: 550px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}
.icon-appear:hover #icon_appear{
  opacity: 1;
}

</style>

<script>
  $(document).ready(function(){
    $('.bxslider').bxSlider();
  });
</script>

app/views/posts/show.html.erb
<% @post.pics.each do |x| %>
  <div class="container text-center">
    <%= image_tag(x.image.url, style: " max-width:1100px;" )%>
  </div>
  <br> <br> 
<%end%>